### ISSUE TITLE
Error sm30 with paremeters

### ISSUE THREAD

**Issue by JavierRodriguezPrieto** [ysichov/SDE#2]
Hello,

First of all good work.

I discovered this issue, when you open a sm30 with parameters its appearing a dump:

![image](https://user-images.githubusercontent.com/54849683/94995812-a9fc8a80-0598-11eb-9ed5-d6788ca1f590.png)

this is when you open an sm30 with parameters:

![image](https://user-images.githubusercontent.com/54849683/94995824-bc76c400-0598-11eb-9f6d-f242969fd445.png)

This is an standard sm30:

V_CNVMBTCONFLICT

Thanks!

**Comment by ysichov** [comment]
Thanks for test. I don't have view V_CNVMBTCONFLICT on my systems. Can you send SE11 photo with view fields?

**Comment by ysichov** [comment]
Thanks for test. Corrected.
